[package]
name = "webapp"
version = "0.1.0"
authors = ["mue"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cli argument handling
clap = "2.33.3"
# web framework
actix-web = "3"
# http client
ureq = "2.1.1"
